### ISSUE TITLE
CMake generate android-libraries-build does not generate nCine-android-external

### ISSUE THREAD

**Issue by Soft-me** [nCine/nCine#1]
I follow the Build for Android,  after building the dependency libraries, I try to build the nCine library
, and I got error:
![image](https://user-images.githubusercontent.com/35207058/77843023-8f052400-71cb-11ea-9ba2-f9c6a256540b.png)

![image](https://user-images.githubusercontent.com/35207058/77842866-ea361700-71c9-11ea-9d6a-4348e1026d7f.png)
I thought maybe I need to build the solution just like generating nCine-external. I open Visual Studio 2019 and build the solution, but I got error:
```
Performing configure step for 'project_ogg'
. \configure' is not recognized as an internal or external command
```
I am very interesing at this game engine.
Did I misunderstand something or doing something wrong？

**Comment by encelo** [comment]
Hi @Soft-me, sorry for not replying earlier, GitHub didn't send me any notification. :weary: 

You can either compile the [nCine-android-libraries](https://github.com/nCine/nCine-android-libraries) yourself by following the [Build for Android](https://ncine.github.io/build-android/) instructions page on the website, or use the [ncline](https://github.com/nCine/ncline) command line tool (watch the [video tutorials](https://ncine.github.io/video-tutorials/) to understand how to use it) or [download](https://github.com/nCine/nCine-libraries-artifacts/branches/all) them from the continuous integration.

Let me know if you have any other issue and join our [Discord](https://discord.gg/495ab6Y) server to chat with me and the other developers.
