### ISSUE TITLE
Build nCine with the OpenGL ES support (on Linux).

### ISSUE THREAD

**Issue by SpacingBat3** [nCine/nCine#12]
## Info
- Hardware: [![rpi-logo](https://github.com/iiiypuk/rpi-icon/raw/master/16.png)](https://www.raspberrypi.org)`Raspberry Pi 4B`
- Platform: `GNU/Linux`
- Architecture: `aarch64`
- nCine release: `master` commit 1b7de7d
## Description
Currently building the nCine with the test app forces the use of the OpenGL 3.3, even if the device doesn't fully support it, but it works with OpenGL ES 3.0. The built itself will finish successfully, but the test application won't work, when trying it on the device supporting OpenGL >3.3 or doesn't supporting it at all, which is the case for most ARM devices.

## Expectations:
The test apps will run using the GLES 3.0 backend on the ARM devices working under Linux distributions.

## Results:
<pre><font color="#8D9197">- HH:MM:SS  </font><span style="background-color:#E07474"><font color="#3F3F3F">[L6]</font></span> - void ncine::SdlGfxDevice::initDevice() -&gt;<b> SDL_GL_CreateContext failed: Could not create GL context: GLXBadFBConfig</b></pre>
(anonymised time)

## Currently known workarounds:
- Use `MESA_GL_VERSION_OVERRIDE=3.3` to force the use of the OpenGL 3.3, even if it isn't supported by hardware (may fail if hardware/software supports GLES API only).
    - **NOTE:** This workaround works fine with the Raspberry Pi 4B device.

**Comment by encelo** [comment]
I would like to buy a Raspberry Pi and/or an ODROID-Go Super also for this specific issue.
When I added the support for ANGLE I knew that OpenGL ES on desktop was pretty much supported, but I haven't bought any device to test it on Linux yet.

I know for sure that [Fahien](https://github.com/Fahien) has managed to run [ncJump](https://github.com/Fahien/ncJump/) on his ODROID-Go Advance as shown on [Twitter](https://twitter.com/Fahien/status/1353038480646033409). 💪🏻
