### ISSUE TITLE
What about a package manager?

### ISSUE THREAD

**Issue by Trimsku** [nCine/nCine#14]
If I weren't a game creator, it would take me time to find all the packages.
But what if you try to add a package manager for faster build, for example, conan?

**Comment by encelo** [comment]
The dependency libraries are provided in binary format for all supported platforms in the [nCine-libraries-artifacts](https://github.com/nCine/nCine-libraries-artifacts/branches/all) repository.
The users willing to recompile them (either in release or in debug) can download the [nCine-libraries](https://github.com/nCine/nCine-libraries) and the [nCine-android-libraries](https://github.com/nCine/nCine-android-libraries) repositories and use the CMake scripts by following the build instructions on the website.

You are, of course, free to support Conan and reopen this task. 😃
