### ISSUE TITLE
error while loading shared libraries: libGLEW.so.2.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 2439905184** [nCine/nCine#20]
ncine version: nCine-2020.05.r307-27869d7-Linux-GCC
system:linux (ubuntu based) Chinese deepin linux.
![2023-03-30_21-30](https://user-images.githubusercontent.com/29478722/228852139-2e58a128-500d-45d4-a371-f47217236850.png)
![image](https://user-images.githubusercontent.com/29478722/228852522-79efd51e-55cc-4493-896a-6d6efb1e214f.png)
seems there is no libglew.so.2.2 , what's wrong?

**Comment by 2439905184** [comment]
./apptest_font
then show can not find libglew but I have installed it (no 2.2.so version)

**Comment by encelo** [comment]
> seems there is no libglew.so.2.2 , what's wrong?

You can find GLEW 2.2.0 on the [Sourceforge](https://sourceforge.net/projects/glew/) project page.

> then show can not find libglew but I have installed it (no 2.2.so version)

If your distribution does not provide the required libraries, you can clone the [nCine-libraries](https://github.com/nCine/nCine-libraries/) repository to compile them yourself by following those [instructions](https://github.com/nCine/nCine/wiki/Build-for-Linux).
You can also use [ncline](https://github.com/nCine/ncline), the command line tool for building the libraries and the framework.
