### ISSUE TITLE
Please support MSYS2 MINGW64

### ISSUE THREAD

**Issue by iahung** [nCine/nCine#22]

**Comment by encelo** [comment]
Hi @iahung, MinGW64 is already supported since several years.
You can download the compiled [artifacts](https://github.com/nCine/nCine-artifacts/branches/all?query=mingw) or [compile](https://github.com/nCine/nCine/wiki/Build-for-Windows#msys2-and-mingw-w64) it.

**Comment by iahung** [comment]
Building with the SDL2 backend is currently failing. The default GLFW backend is building fine, though.

**Comment by encelo** [comment]
Can you post the error you get? I use [MSYS2](https://www.msys2.org/) and I'm able to build `master` with SDL2 as the preferred backend.

**Comment by iahung** [comment]
I'm tried and able to build with both the three backends now. As I recall, it failed to build when I don't have GLFW installed that it automatically falls back to SDL2 as the backend. But I can't test this case as I have both GLFW, SDL2 and QT5 installed now. You could dismiss this issue.
