### ISSUE TITLE
Question: Is cross-building from one OS to another supported? 

### ISSUE THREAD

**Issue by MetalMaxMX** [nCine/nCine#23]
Hi! I've checked the wiki of the project and it has instructions on building for every individual platform that the nCine engine supports. What I would like to know is, is compiling from one host (Linux) to another (example, Windows) possible and supported? Since nCine already supports building with MinGW through MSYS on Windows natively, I was thinking if it was possible to do the same with the copy of mingw that Linux itself provides on various repositories. 

Or is the recommended/suggested approach to use CIs and or VMs/Windows hosts to build projects to this? (I understand that the case of macOS is much more difficult due to authentication issues and certs and all, so I am talking here primarily about Linux to Win)

**Comment by MetalMaxMX** [comment]
Just to know. But the binaries you compiled from the Linux host through MinGW-w64 were able to run on the Windows host, right?

**Comment by encelo** [comment]
> Just to know. But the binaries you compiled from the Linux host through MinGW-w64 were able to run on the Windows host, right?

It was a long time ago, I don't remember the details. :thinking:
Anyway, as I needed a Windows installation to test it, I decided to configure a dual boot, install Visual Studio, and build, debug and run on the same system.
If you decide to configure a cross-compile toolchain, let me know if you manage to build and run the framework. 😉

**Comment by MetalMaxMX** [comment]
Oh, okay. Personally I just wanted to know if it was possible to do so, and any confirmation is good enough for me. I do know someone who did managed to get another codebase cross-compiled from C++ so I think for this project it'll be feasible. I might try at some point but hopefully it isn't too bad
